batch_size: 128
lr: 1e-4
weight_decay: 1e-5
pool_size: 50
gen:
  ngf: 64
#  ngf: 16
#  which_model_netG: resnet_blocks
  which_model_netG: resnet_6blocks
  norm: instance
dis:
  ndf: 64
#  ndf: 16
  which_model_netD: basic
