batch_size: 32
base_lr: 1e-4
betas: (0.5, 0.999)
weight_decay: 1e-5
pool_size: 50
weight:
  alpha: 1.0
  gamma: 1.0
  beta: 10.0
  mu: 10.0
  eta: 1.0
  new: 1.0
gen_init:
  n_ch: 64
  n_hidden: 5
  n_resblock: 4
dis_init:
  n_ch: 64
